"""
Pydantic schemas for request/response validation
"""

# 原有schemas
from app.schemas.requests import ContactFormRequest

# 新增schemas（从 schemas.py 导入）
from app.schemas.schemas import (
    BookingCreate,
    BookingResponse,
    BookingUpdate,
    EventCreate,
    EventRegistrationCreate,
    EventResponse,
    FAQCreate,
    FAQResponse,
    FAQUpdate,
    FileDownloadCreate,
    FileDownloadResponse,
    FileDownloadUpdate,
    PostCategoryCreate,
    PostCategoryResponse,
    PostCreate,
    PostResponse,
    PostUpdate,
    ProductCreate,
    ProductResponse,
    ProductUpdate,
    TeamMemberCreate,
    TeamMemberResponse,
    TeamMemberUpdate,
    UserLogin,
    UserRegister,
    UserResponse,
    UserUpdate,
    VideoCreate,
    VideoResponse,
    VideoUpdate,
)

__all__ = [
    "BookingCreate",
    "BookingResponse",
    "BookingUpdate",
    "ContactFormRequest",
    "EventCreate",
    "EventRegistrationCreate",
    "EventResponse",
    "FAQCreate",
    "FAQResponse",
    "FAQUpdate",
    "FileDownloadCreate",
    "FileDownloadResponse",
    "FileDownloadUpdate",
    "PostCategoryCreate",
    "PostCategoryResponse",
    "PostCreate",
    "PostResponse",
    "PostUpdate",
    "ProductCreate",
    "ProductResponse",
    "ProductUpdate",
    "TeamMemberCreate",
    "TeamMemberResponse",
    "TeamMemberUpdate",
    "UserLogin",
    "UserRegister",
    "UserResponse",
    "UserUpdate",
    "VideoCreate",
    "VideoResponse",
    "VideoUpdate",
]
