-- 为博文教育中心扩展 FAQ 内容
-- 执行时间: 2025-11-16
-- 说明: 添加 15 个新的中英双语 FAQ，覆盖入学、课程、费用、考试、师资、活动等类别

-- 入学相关 FAQ (3个)
INSERT INTO faq (category, question, answer, question_en, answer_en, question_zh, answer_zh, sort_order, is_visible, is_pinned, view_count, helpful_count, unhelpful_count, created_at, updated_at)
VALUES
(
  'Enrolment',
  'What are the age requirements for enrollment?',
  '<p>We welcome children from ages 4 to 16 across our different programmes:</p><ul><li><strong>Chinese School:</strong> Ages 4-16, grouped by ability level rather than age</li><li><strong>Chess Club:</strong> Ages 5-16, from beginners to advanced players</li><li><strong>Badminton Club:</strong> Ages 6-16, all skill levels welcome</li></ul><p>For younger children (under 5), please contact us for individual assessment.</p>',
  'What are the age requirements for enrollment?',
  '<p>We welcome children from ages 4 to 16 across our different programmes:</p><ul><li><strong>Chinese School:</strong> Ages 4-16, grouped by ability level rather than age</li><li><strong>Chess Club:</strong> Ages 5-16, from beginners to advanced players</li><li><strong>Badminton Club:</strong> Ages 6-16, all skill levels welcome</li></ul><p>For younger children (under 5), please contact us for individual assessment.</p>',
  '入学年龄要求是什么？',
  '<p>我们欢迎4至16岁的儿童参加我们的不同项目：</p><ul><li><strong>中文学校：</strong>4-16岁，按能力水平而非年龄分班</li><li><strong>国际象棋俱乐部：</strong>5-16岁，从初学者到高级选手</li><li><strong>羽毛球俱乐部：</strong>6-16岁，欢迎所有技能水平</li></ul><p>对于年龄较小的儿童（5岁以下），请联系我们进行个别评估。</p>',
  4,
  1,
  0,
  0,
  0,
  0,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'Enrolment',
  'Do I need to book a trial class before enrolling?',
  '<p>While not mandatory, we <strong>highly recommend</strong> booking a free trial class before enrollment. This allows:</p><ul><li>Your child to experience our teaching style and classroom environment</li><li>Our teachers to assess your child''s current level and recommend the most suitable class</li><li>You to meet our staff and ask any questions</li></ul><p>Trial classes are available for all programmes. Please book at least 2 days in advance through our website or by phone.</p>',
  'Do I need to book a trial class before enrolling?',
  '<p>While not mandatory, we <strong>highly recommend</strong> booking a free trial class before enrollment. This allows:</p><ul><li>Your child to experience our teaching style and classroom environment</li><li>Our teachers to assess your child''s current level and recommend the most suitable class</li><li>You to meet our staff and ask any questions</li></ul><p>Trial classes are available for all programmes. Please book at least 2 days in advance through our website or by phone.</p>',
  '入学前需要预约试听课吗？',
  '<p>虽然不是强制性的，但我们<strong>强烈建议</strong>在入学前预约免费试听课。这样可以：</p><ul><li>让您的孩子体验我们的教学风格和课堂环境</li><li>让我们的老师评估孩子当前水平并推荐最合适的班级</li><li>让您与我们的员工见面并提出任何问题</li></ul><p>所有项目均提供试听课。请至少提前2天通过网站或电话预约。</p>',
  5,
  1,
  0,
  0,
  0,
  0,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'Enrolment',
  'How are classes divided and allocated?',
  '<p>Class allocation is based on <strong>ability and learning pace</strong> rather than just age:</p><ul><li><strong>Initial Assessment:</strong> During the trial class or first session, teachers assess each student''s level</li><li><strong>Chinese School:</strong> Classes are divided by HSK/YCT levels (beginner to advanced)</li><li><strong>Chess Club:</strong> Grouped by chess rating and experience</li><li><strong>Badminton Club:</strong> Split by skill level and physical ability</li></ul><p>We maintain small class sizes (typically 8-12 students) to ensure personalized attention. Students can move between levels as they progress.</p>',
  'How are classes divided and allocated?',
  '<p>Class allocation is based on <strong>ability and learning pace</strong> rather than just age:</p><ul><li><strong>Initial Assessment:</strong> During the trial class or first session, teachers assess each student''s level</li><li><strong>Chinese School:</strong> Classes are divided by HSK/YCT levels (beginner to advanced)</li><li><strong>Chess Club:</strong> Grouped by chess rating and experience</li><li><strong>Badminton Club:</strong> Split by skill level and physical ability</li></ul><p>We maintain small class sizes (typically 8-12 students) to ensure personalized attention. Students can move between levels as they progress.</p>',
  '如何划分和分配班级？',
  '<p>班级分配基于<strong>能力和学习进度</strong>而非仅仅年龄：</p><ul><li><strong>初步评估：</strong>在试听课或首节课期间，老师评估每位学生的水平</li><li><strong>中文学校：</strong>按HSK/YCT等级划分（从初级到高级）</li><li><strong>国际象棋俱乐部：</strong>按棋力等级和经验分组</li><li><strong>羽毛球俱乐部：</strong>按技能水平和身体能力分班</li></ul><p>我们保持小班教学（通常8-12名学生），以确保个性化关注。学生可以随着进步在不同级别之间流动。</p>',
  6,
  1,
  0,
  0,
  0,
  0,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),

-- 课程相关 FAQ (4个)
(
  'Courses',
  'How long is each class and term?',
  '<p>Our class and term structure varies by programme:</p><ul><li><strong>Chinese School:</strong> 2-hour classes, once per week, 12-week terms (3 terms per year)</li><li><strong>Chess Club:</strong> 1.5-hour sessions, once per week, continuous enrollment with half-term breaks</li><li><strong>Badminton Club:</strong> 1.5-hour sessions, once or twice per week, flexible term options</li><li><strong>Tuition Centre:</strong> 1-hour sessions, customized schedule based on student needs</li></ul><p>We follow the UK school calendar with breaks during major holidays.</p>',
  'How long is each class and term?',
  '<p>Our class and term structure varies by programme:</p><ul><li><strong>Chinese School:</strong> 2-hour classes, once per week, 12-week terms (3 terms per year)</li><li><strong>Chess Club:</strong> 1.5-hour sessions, once per week, continuous enrollment with half-term breaks</li><li><strong>Badminton Club:</strong> 1.5-hour sessions, once or twice per week, flexible term options</li><li><strong>Tuition Centre:</strong> 1-hour sessions, customized schedule based on student needs</li></ul><p>We follow the UK school calendar with breaks during major holidays.</p>',
  '每节课和学期多长？',
  '<p>我们的课程和学期结构因项目而异：</p><ul><li><strong>中文学校：</strong>每周一次，每次2小时，12周一学期（每年3个学期）</li><li><strong>国际象棋俱乐部：</strong>每周一次，每次1.5小时，持续招生，半学期休息</li><li><strong>羽毛球俱乐部：</strong>每周一次或两次，每次1.5小时，灵活的学期选项</li><li><strong>补习中心：</strong>每次1小时，根据学生需求定制时间表</li></ul><p>我们遵循英国学校日历，在主要节假日期间休息。</p>',
  7,
  1,
  0,
  0,
  0,
  0,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'Courses',
  'What textbooks and materials do you use?',
  '<p>We use internationally recognized materials tailored to each programme:</p><ul><li><strong>Chinese School:</strong> <em>YCT Standard Course</em> and <em>HSK Standard Course</em> textbooks, plus supplementary materials developed in-house</li><li><strong>Chess Club:</strong> ECF (English Chess Federation) curriculum materials and online training platforms</li><li><strong>Badminton Club:</strong> BWF (Badminton World Federation) coaching manuals and video resources</li></ul><p>All core textbooks are included in term fees. Students only need to bring their own stationery/equipment.</p>',
  'What textbooks and materials do you use?',
  '<p>We use internationally recognized materials tailored to each programme:</p><ul><li><strong>Chinese School:</strong> <em>YCT Standard Course</em> and <em>HSK Standard Course</em> textbooks, plus supplementary materials developed in-house</li><li><strong>Chess Club:</strong> ECF (English Chess Federation) curriculum materials and online training platforms</li><li><strong>Badminton Club:</strong> BWF (Badminton World Federation) coaching manuals and video resources</li></ul><p>All core textbooks are included in term fees. Students only need to bring their own stationery/equipment.</p>',
  '你们使用什么教材？',
  '<p>我们使用国际认可的教材，针对每个项目量身定制：</p><ul><li><strong>中文学校：</strong>《YCT标准教程》和《HSK标准教程》，加上内部开发的补充材料</li><li><strong>国际象棋俱乐部：</strong>英格兰国际象棋联合会（ECF）课程材料和在线培训平台</li><li><strong>羽毛球俱乐部：</strong>世界羽联（BWF）教练手册和视频资源</li></ul><p>所有核心教材包含在学期费用中。学生只需自备文具/设备。</p>',
  8,
  1,
  0,
  0,
  0,
  0,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'Courses',
  'What time are classes held?',
  '<p>Classes are primarily held on <strong>Saturdays and Sundays</strong> to accommodate school-age children:</p><ul><li><strong>Saturday:</strong> 9:00 AM - 12:00 PM (Chinese School), 1:00 PM - 5:00 PM (Chess & Badminton)</li><li><strong>Sunday:</strong> 9:00 AM - 12:00 PM (Chinese School), 1:00 PM - 5:00 PM (Chess & Badminton)</li><li><strong>Weekday Evenings:</strong> Limited availability for tuition centre (Mon-Fri, 4:00 PM - 7:00 PM)</li></ul><p>Exact timings vary by level and programme. We''ll confirm your child''s specific schedule after enrollment.</p>',
  'What time are classes held?',
  '<p>Classes are primarily held on <strong>Saturdays and Sundays</strong> to accommodate school-age children:</p><ul><li><strong>Saturday:</strong> 9:00 AM - 12:00 PM (Chinese School), 1:00 PM - 5:00 PM (Chess & Badminton)</li><li><strong>Sunday:</strong> 9:00 AM - 12:00 PM (Chinese School), 1:00 PM - 5:00 PM (Chess & Badminton)</li><li><strong>Weekday Evenings:</strong> Limited availability for tuition centre (Mon-Fri, 4:00 PM - 7:00 PM)</li></ul><p>Exact timings vary by level and programme. We''ll confirm your child''s specific schedule after enrollment.</p>',
  '上课时间是什么时候？',
  '<p>课程主要在<strong>周六和周日</strong>进行，以适应学龄儿童：</p><ul><li><strong>周六：</strong>上午9:00-12:00（中文学校），下午1:00-5:00（国际象棋和羽毛球）</li><li><strong>周日：</strong>上午9:00-12:00（中文学校），下午1:00-5:00（国际象棋和羽毛球）</li><li><strong>工作日晚间：</strong>补习中心有限名额（周一至周五，下午4:00-7:00）</li></ul><p>具体时间因级别和项目而异。入学后我们会确认您孩子的具体时间表。</p>',
  9,
  1,
  0,
  0,
  0,
  0,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'Courses',
  'What does the curriculum cover?',
  '<p>Our curriculum is comprehensive and goal-oriented:</p><ul><li><strong>Chinese School:</strong> Listening, speaking, reading, and writing skills. Focus on Pinyin, character recognition, grammar, and cultural understanding. Preparation for HSK/YCT exams.</li><li><strong>Chess Club:</strong> Opening theory, middle-game tactics, endgame techniques, tournament preparation, and competitive play.</li><li><strong>Badminton Club:</strong> Footwork, strokes (clear, drop, smash), serves, doubles strategy, match play, and physical conditioning.</li></ul><p>All programmes include regular assessments, progress reports, and opportunities for competitions or examinations.</p>',
  'What does the curriculum cover?',
  '<p>Our curriculum is comprehensive and goal-oriented:</p><ul><li><strong>Chinese School:</strong> Listening, speaking, reading, and writing skills. Focus on Pinyin, character recognition, grammar, and cultural understanding. Preparation for HSK/YCT exams.</li><li><strong>Chess Club:</strong> Opening theory, middle-game tactics, endgame techniques, tournament preparation, and competitive play.</li><li><strong>Badminton Club:</strong> Footwork, strokes (clear, drop, smash), serves, doubles strategy, match play, and physical conditioning.</li></ul><p>All programmes include regular assessments, progress reports, and opportunities for competitions or examinations.</p>',
  '课程内容涵盖哪些方面？',
  '<p>我们的课程全面且目标明确：</p><ul><li><strong>中文学校：</strong>听、说、读、写技能。重点是拼音、汉字识别、语法和文化理解。为HSK/YCT考试做准备。</li><li><strong>国际象棋俱乐部：</strong>开局理论、中局战术、残局技巧、锦标赛准备和竞技对弈。</li><li><strong>羽毛球俱乐部：</strong>步法、击球（高远球、吊球、杀球）、发球、双打策略、比赛对打和体能训练。</li></ul><p>所有项目均包括定期评估、进度报告以及参加比赛或考试的机会。</p>',
  10,
  1,
  0,
  0,
  0,
  0,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),

-- 费用相关 FAQ (2个)
(
  'Fees & Payment',
  'What payment methods do you accept?',
  '<p>We offer flexible payment options for your convenience:</p><ul><li><strong>Bank Transfer:</strong> Our preferred method (bank details provided upon enrollment)</li><li><strong>Online Payment:</strong> Via our secure payment portal (credit/debit cards accepted)</li><li><strong>Cash:</strong> Accepted at our centre during office hours</li><li><strong>Cheque:</strong> Payable to "Bowen Education Manchester Limited"</li></ul><p>Payment is due at the start of each term. We also offer sibling discounts (10% off for second child, 15% off for third child onwards).</p>',
  'What payment methods do you accept?',
  '<p>We offer flexible payment options for your convenience:</p><ul><li><strong>Bank Transfer:</strong> Our preferred method (bank details provided upon enrollment)</li><li><strong>Online Payment:</strong> Via our secure payment portal (credit/debit cards accepted)</li><li><strong>Cash:</strong> Accepted at our centre during office hours</li><li><strong>Cheque:</strong> Payable to "Bowen Education Manchester Limited"</li></ul><p>Payment is due at the start of each term. We also offer sibling discounts (10% off for second child, 15% off for third child onwards).</p>',
  '你们接受哪些付款方式？',
  '<p>我们提供灵活的付款方式：</p><ul><li><strong>银行转账：</strong>我们的首选方式（入学时提供银行详情）</li><li><strong>在线支付：</strong>通过我们的安全支付门户（接受信用卡/借记卡）</li><li><strong>现金：</strong>在办公时间内在我们中心接受</li><li><strong>支票：</strong>抬头为"Bowen Education Manchester Limited"</li></ul><p>费用在每学期开始时支付。我们还提供兄弟姐妹折扣（第二个孩子10%折扣，第三个孩子起15%折扣）。</p>',
  11,
  1,
  0,
  0,
  0,
  0,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'Fees & Payment',
  'What is your refund and cancellation policy?',
  '<p>Our refund policy is designed to be fair and transparent:</p><ul><li><strong>Before Term Starts:</strong> Full refund minus £20 administration fee</li><li><strong>Within First 2 Weeks:</strong> 75% refund of remaining term fees</li><li><strong>After 2 Weeks:</strong> No refunds, but you can transfer to next term or another programme</li><li><strong>Medical/Emergency:</strong> Case-by-case consideration with supporting documentation</li></ul><p>For absences due to illness or holidays, we offer make-up classes subject to availability. Please provide at least 24 hours notice for missed classes.</p>',
  'What is your refund and cancellation policy?',
  '<p>Our refund policy is designed to be fair and transparent:</p><ul><li><strong>Before Term Starts:</strong> Full refund minus £20 administration fee</li><li><strong>Within First 2 Weeks:</strong> 75% refund of remaining term fees</li><li><strong>After 2 Weeks:</strong> No refunds, but you can transfer to next term or another programme</li><li><strong>Medical/Emergency:</strong> Case-by-case consideration with supporting documentation</li></ul><p>For absences due to illness or holidays, we offer make-up classes subject to availability. Please provide at least 24 hours notice for missed classes.</p>',
  '你们的退款和取消政策是什么？',
  '<p>我们的退款政策公平透明：</p><ul><li><strong>学期开始前：</strong>全额退款减去£20管理费</li><li><strong>前2周内：</strong>剩余学期费用的75%退款</li><li><strong>2周后：</strong>不退款，但可以转到下学期或其他项目</li><li><strong>医疗/紧急情况：</strong>根据支持文件逐案考虑</li></ul><p>因疾病或假期缺席，我们提供补课（视名额而定）。请至少提前24小时通知缺课。</p>',
  12,
  1,
  0,
  0,
  0,
  0,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),

-- 考试相关 FAQ (3个)
(
  'Exams',
  'Can my child take HSK/YCT exams through your school?',
  '<p><strong>Yes!</strong> We are an authorized HSK/YCT examination centre:</p><ul><li>We organize group exam sessions twice a year (June and December)</li><li>Students receive exam preparation classes in the lead-up to tests</li><li>Mock exams are provided to familiarize students with the format</li><li>Exam registration is handled by our administrative team</li><li>Results are typically available 4-6 weeks after the exam</li></ul><p>The exam fees are separate from tuition fees. We recommend students take exams when teachers feel they are ready, typically after completing the corresponding level coursebook.</p>',
  'Can my child take HSK/YCT exams through your school?',
  '<p><strong>Yes!</strong> We are an authorized HSK/YCT examination centre:</p><ul><li>We organize group exam sessions twice a year (June and December)</li><li>Students receive exam preparation classes in the lead-up to tests</li><li>Mock exams are provided to familiarize students with the format</li><li>Exam registration is handled by our administrative team</li><li>Results are typically available 4-6 weeks after the exam</li></ul><p>The exam fees are separate from tuition fees. We recommend students take exams when teachers feel they are ready, typically after completing the corresponding level coursebook.</p>',
  '我的孩子可以通过你们学校参加HSK/YCT考试吗？',
  '<p><strong>可以！</strong>我们是授权的HSK/YCT考试中心：</p><ul><li>我们每年组织两次集体考试（6月和12月）</li><li>学生在考试前会接受考试准备课程</li><li>提供模拟考试让学生熟悉考试形式</li><li>考试报名由我们的行政团队处理</li><li>成绩通常在考试后4-6周内公布</li></ul><p>考试费用独立于学费。我们建议学生在老师认为准备好时参加考试，通常是在完成相应级别教材后。</p>',
  13,
  1,
  0,
  0,
  0,
  0,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'Exams',
  'Do you offer GCSE or A-Level Chinese preparation?',
  '<p><strong>Yes, we do!</strong> Our GCSE and A-Level Chinese preparation courses are available through our Tuition Centre:</p><ul><li><strong>GCSE Chinese:</strong> Full syllabus coverage (AQA/Edexcel), exam technique training, past paper practice</li><li><strong>A-Level Chinese:</strong> Advanced reading, writing, listening, speaking skills, cultural topics, essay writing</li></ul><p>These are intensive courses typically running during term time and school holidays. Class sizes are limited to 6 students for maximum attention. Please contact us for current schedules and availability.</p>',
  'Do you offer GCSE or A-Level Chinese preparation?',
  '<p><strong>Yes, we do!</strong> Our GCSE and A-Level Chinese preparation courses are available through our Tuition Centre:</p><ul><li><strong>GCSE Chinese:</strong> Full syllabus coverage (AQA/Edexcel), exam technique training, past paper practice</li><li><strong>A-Level Chinese:</strong> Advanced reading, writing, listening, speaking skills, cultural topics, essay writing</li></ul><p>These are intensive courses typically running during term time and school holidays. Class sizes are limited to 6 students for maximum attention. Please contact us for current schedules and availability.</p>',
  '你们提供GCSE或A-Level中文考试培训吗？',
  '<p><strong>是的！</strong>我们的GCSE和A-Level中文备考课程通过补习中心提供：</p><ul><li><strong>GCSE中文：</strong>完整大纲覆盖（AQA/Edexcel），考试技巧培训，真题练习</li><li><strong>A-Level中文：</strong>高级读、写、听、说技能，文化主题，论文写作</li></ul><p>这些是强化课程，通常在学期和学校假期期间进行。班级人数限制为6名学生，以确保最大关注。请联系我们了解当前时间表和名额。</p>',
  14,
  1,
  0,
  0,
  0,
  0,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'Exams',
  'What is the pass rate for your students in exams?',
  '<p>We are proud of our students'' excellent examination results:</p><ul><li><strong>HSK/YCT Exams:</strong> 95%+ pass rate over the past 3 years, with 70% achieving high scores (180+/200)</li><li><strong>GCSE Chinese:</strong> 100% pass rate, with 85% achieving Grade 7-9</li><li><strong>A-Level Chinese:</strong> 98% pass rate, with 75% achieving A*-A grades</li><li><strong>Chess Tournaments:</strong> Multiple students achieving county and national rankings</li></ul><p>These results reflect our rigorous teaching standards, structured curriculum, and dedicated teachers. Individual results vary based on attendance and effort.</p>',
  'What is the pass rate for your students in exams?',
  '<p>We are proud of our students'' excellent examination results:</p><ul><li><strong>HSK/YCT Exams:</strong> 95%+ pass rate over the past 3 years, with 70% achieving high scores (180+/200)</li><li><strong>GCSE Chinese:</strong> 100% pass rate, with 85% achieving Grade 7-9</li><li><strong>A-Level Chinese:</strong> 98% pass rate, with 75% achieving A*-A grades</li><li><strong>Chess Tournaments:</strong> Multiple students achieving county and national rankings</li></ul><p>These results reflect our rigorous teaching standards, structured curriculum, and dedicated teachers. Individual results vary based on attendance and effort.</p>',
  '你们学生的考试通过率如何？',
  '<p>我们为学生的优异考试成绩感到自豪：</p><ul><li><strong>HSK/YCT考试：</strong>过去3年95%+通过率，70%的学生获得高分（180+/200）</li><li><strong>GCSE中文：</strong>100%通过率，85%获得7-9分</li><li><strong>A-Level中文：</strong>98%通过率，75%获得A*-A等级</li><li><strong>国际象棋锦标赛：</strong>多名学生获得郡级和国家级排名</li></ul><p>这些成绩反映了我们严格的教学标准、结构化的课程和敬业的教师。个人成绩因出勤率和努力程度而异。</p>',
  15,
  1,
  0,
  0,
  0,
  0,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),

-- 师资相关 FAQ (2个)
(
  'Teachers',
  'What are the qualifications of your teachers?',
  '<p>All our teachers are highly qualified and experienced professionals:</p><ul><li><strong>Chinese Teachers:</strong> Native speakers with teaching qualifications (CTCSOL or equivalent), university degrees in Chinese language/education, minimum 3 years teaching experience</li><li><strong>Chess Coaches:</strong> ECF qualified coaches, active competitive players (minimum rating 1800), DBS checked</li><li><strong>Badminton Coaches:</strong> BWF/Badminton England certified coaches, Level 2+ qualifications, experience in youth coaching</li></ul><p>All staff undergo enhanced DBS checks and regular safeguarding training. Many have additional specializations in child psychology and special educational needs.</p>',
  'What are the qualifications of your teachers?',
  '<p>All our teachers are highly qualified and experienced professionals:</p><ul><li><strong>Chinese Teachers:</strong> Native speakers with teaching qualifications (CTCSOL or equivalent), university degrees in Chinese language/education, minimum 3 years teaching experience</li><li><strong>Chess Coaches:</strong> ECF qualified coaches, active competitive players (minimum rating 1800), DBS checked</li><li><strong>Badminton Coaches:</strong> BWF/Badminton England certified coaches, Level 2+ qualifications, experience in youth coaching</li></ul><p>All staff undergo enhanced DBS checks and regular safeguarding training. Many have additional specializations in child psychology and special educational needs.</p>',
  '你们教师的资质如何？',
  '<p>我们所有教师都是高素质和经验丰富的专业人士：</p><ul><li><strong>中文教师：</strong>母语人士，持有教学资格证（CTCSOL或同等学历），拥有中文语言/教育大学学位，至少3年教学经验</li><li><strong>国际象棋教练：</strong>ECF认证教练，活跃的竞技选手（最低等级1800），通过DBS审查</li><li><strong>羽毛球教练：</strong>BWF/英格兰羽毛球协会认证教练，2级以上资格，有青少年教练经验</li></ul><p>所有员工都经过增强型DBS审查和定期保护培训。许多教师还在儿童心理学和特殊教育需求方面有额外专长。</p>',
  16,
  1,
  0,
  0,
  0,
  0,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'Teachers',
  'What is your student-to-teacher ratio?',
  '<p>We maintain excellent student-to-teacher ratios to ensure quality learning:</p><ul><li><strong>Chinese School:</strong> Average 10:1 ratio (max 12 students per class)</li><li><strong>Chess Club:</strong> 8:1 ratio for group sessions, 1:1 for private coaching</li><li><strong>Badminton Club:</strong> 10:1 ratio with assistant coaches for larger groups</li><li><strong>Tuition Centre:</strong> Maximum 6:1 for group classes, 1:1 for private tutoring</li></ul><p>Teaching assistants support main teachers in larger classes, and we often have parent volunteers helping with younger age groups. This ensures every child receives individual attention and feedback.</p>',
  'What is your student-to-teacher ratio?',
  '<p>We maintain excellent student-to-teacher ratios to ensure quality learning:</p><ul><li><strong>Chinese School:</strong> Average 10:1 ratio (max 12 students per class)</li><li><strong>Chess Club:</strong> 8:1 ratio for group sessions, 1:1 for private coaching</li><li><strong>Badminton Club:</strong> 10:1 ratio with assistant coaches for larger groups</li><li><strong>Tuition Centre:</strong> Maximum 6:1 for group classes, 1:1 for private tutoring</li></ul><p>Teaching assistants support main teachers in larger classes, and we often have parent volunteers helping with younger age groups. This ensures every child receives individual attention and feedback.</p>',
  '你们的师生比例是多少？',
  '<p>我们保持优秀的师生比例以确保优质学习：</p><ul><li><strong>中文学校：</strong>平均10:1比例（每班最多12名学生）</li><li><strong>国际象棋俱乐部：</strong>小组课程8:1比例，私人教练1:1</li><li><strong>羽毛球俱乐部：</strong>10:1比例，较大小组配有助教</li><li><strong>补习中心：</strong>小组课程最多6:1，私人辅导1:1</li></ul><p>助教在较大班级中支持主教师，我们经常有家长志愿者帮助年龄较小的组别。这确保每个孩子都能得到个人关注和反馈。</p>',
  17,
  1,
  0,
  0,
  0,
  0,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),

-- 活动相关 FAQ (2个)
(
  'Activities',
  'Do you organize cultural events and activities?',
  '<p><strong>Yes!</strong> We host a variety of cultural and social events throughout the year:</p><ul><li><strong>Chinese New Year Celebration:</strong> Lion dance, lantern making, traditional performances, and family feast</li><li><strong>Mid-Autumn Festival:</strong> Mooncake making, lantern parade, storytelling</li><li><strong>Dragon Boat Festival:</strong> Zongzi cooking workshop, dragon boat racing (when weather permits)</li><li><strong>Chess Tournaments:</strong> Internal competitions, inter-school matches, county championships</li><li><strong>Badminton Tournaments:</strong> Club championships, friendly matches with other clubs</li><li><strong>Summer Camp:</strong> 2-week intensive programmes combining learning and fun</li></ul><p>These events are open to all students and their families. Check our Events page for upcoming activities.</p>',
  'Do you organize cultural events and activities?',
  '<p><strong>Yes!</strong> We host a variety of cultural and social events throughout the year:</p><ul><li><strong>Chinese New Year Celebration:</strong> Lion dance, lantern making, traditional performances, and family feast</li><li><strong>Mid-Autumn Festival:</strong> Mooncake making, lantern parade, storytelling</li><li><strong>Dragon Boat Festival:</strong> Zongzi cooking workshop, dragon boat racing (when weather permits)</li><li><strong>Chess Tournaments:</strong> Internal competitions, inter-school matches, county championships</li><li><strong>Badminton Tournaments:</strong> Club championships, friendly matches with other clubs</li><li><strong>Summer Camp:</strong> 2-week intensive programmes combining learning and fun</li></ul><p>These events are open to all students and their families. Check our Events page for upcoming activities.</p>',
  '你们会组织文化活动吗？',
  '<p><strong>是的！</strong>我们全年举办各种文化和社交活动：</p><ul><li><strong>春节庆祝：</strong>舞狮、制作灯笼、传统表演和家庭宴会</li><li><strong>中秋节：</strong>制作月饼、灯笼游行、讲故事</li><li><strong>端午节：</strong>粽子烹饪工作坊、赛龙舟（天气允许时）</li><li><strong>国际象棋锦标赛：</strong>内部比赛、校际比赛、郡级锦标赛</li><li><strong>羽毛球锦标赛：</strong>俱乐部锦标赛、与其他俱乐部的友谊赛</li><li><strong>夏令营：</strong>为期2周的强化项目，结合学习和乐趣</li></ul><p>这些活动对所有学生及其家人开放。查看我们的活动页面了解即将举行的活动。</p>',
  18,
  1,
  0,
  0,
  0,
  0,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'Activities',
  'Can parents stay and watch classes?',
  '<p>Our policy on parent observation varies by programme and age group:</p><ul><li><strong>Trial Classes:</strong> Parents are welcome to observe to see our teaching style</li><li><strong>Young Children (under 7):</strong> Parents may observe for the first 2-3 weeks until children settle in</li><li><strong>Regular Classes:</strong> We encourage independent learning, but parents can observe through viewing windows</li><li><strong>Open Days:</strong> We hold quarterly open classes where parents can watch and participate</li></ul><p>We have a comfortable waiting area with refreshments where parents can relax during class times. Free WiFi is available. We also provide regular progress updates via email and parent-teacher meetings each term.</p>',
  'Can parents stay and watch classes?',
  '<p>Our policy on parent observation varies by programme and age group:</p><ul><li><strong>Trial Classes:</strong> Parents are welcome to observe to see our teaching style</li><li><strong>Young Children (under 7):</strong> Parents may observe for the first 2-3 weeks until children settle in</li><li><strong>Regular Classes:</strong> We encourage independent learning, but parents can observe through viewing windows</li><li><strong>Open Days:</strong> We hold quarterly open classes where parents can watch and participate</li></ul><p>We have a comfortable waiting area with refreshments where parents can relax during class times. Free WiFi is available. We also provide regular progress updates via email and parent-teacher meetings each term.</p>',
  '家长可以留下来观看课程吗？',
  '<p>我们对家长观课的政策因项目和年龄组而异：</p><ul><li><strong>试听课：</strong>欢迎家长观课以了解我们的教学风格</li><li><strong>年幼儿童（7岁以下）：</strong>家长可在前2-3周观课直到孩子适应</li><li><strong>常规课程：</strong>我们鼓励独立学习，但家长可通过观察窗观看</li><li><strong>开放日：</strong>我们每季度举办开放课堂，家长可以观看和参与</li></ul><p>我们有舒适的等候区，提供茶点供家长在上课期间休息。提供免费WiFi。我们还通过电子邮件和每学期家长会定期提供进度更新。</p>',
  19,
  1,
  0,
  0,
  0,
  0,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),

-- 其他 FAQ (2个)
(
  'Facilities',
  'Where is your centre located and is parking available?',
  '<p>We are conveniently located in Manchester with excellent transport links:</p><ul><li><strong>Address:</strong> Unit 4, Bowker Vale, Crescent Road, Crumpsall, Manchester M8 5SH</li><li><strong>Public Transport:</strong> Accessible by bus routes 52, 135, 149. 5-minute walk from Bowker Vale tram stop.</li><li><strong>Parking:</strong> Free on-site parking for 30+ cars. Additional street parking available on surrounding roads.</li><li><strong>Facilities:</strong> Fully equipped classrooms, sports hall, computer lab, library, and student lounge.</li></ul><p>Our centre is on the ground floor with wheelchair access and disabled toilet facilities. Drop-off and pick-up zones are clearly marked for safety.</p>',
  'Where is your centre located and is parking available?',
  '<p>We are conveniently located in Manchester with excellent transport links:</p><ul><li><strong>Address:</strong> Unit 4, Bowker Vale, Crescent Road, Crumpsall, Manchester M8 5SH</li><li><strong>Public Transport:</strong> Accessible by bus routes 52, 135, 149. 5-minute walk from Bowker Vale tram stop.</li><li><strong>Parking:</strong> Free on-site parking for 30+ cars. Additional street parking available on surrounding roads.</li><li><strong>Facilities:</strong> Fully equipped classrooms, sports hall, computer lab, library, and student lounge.</li></ul><p>Our centre is on the ground floor with wheelchair access and disabled toilet facilities. Drop-off and pick-up zones are clearly marked for safety.</p>',
  '你们中心位于哪里？有停车位吗？',
  '<p>我们位于曼彻斯特，交通便利：</p><ul><li><strong>地址：</strong>曼彻斯特Crumpsall，Crescent Road，Bowker Vale，Unit 4，邮编M8 5SH</li><li><strong>公共交通：</strong>可乘坐52、135、149路公交车。距离Bowker Vale电车站步行5分钟。</li><li><strong>停车：</strong>现场免费停车位30+个。周围道路有额外街边停车位。</li><li><strong>设施：</strong>设备齐全的教室、体育馆、计算机实验室、图书馆和学生休息室。</li></ul><p>我们的中心位于一层，设有轮椅通道和残疾人卫生间设施。落客和接客区域标示清晰以确保安全。</p>',
  20,
  1,
  0,
  0,
  0,
  0,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'General',
  'How can I contact you for more information?',
  '<p>We''d love to hear from you! You can reach us through multiple channels:</p><ul><li><strong>Phone:</strong> 07888 760868 (Monday-Friday, 9 AM - 5 PM; Saturday-Sunday, 9 AM - 1 PM)</li><li><strong>Email:</strong> <a href="mailto:info@boweneducation.co.uk">info@boweneducation.co.uk</a> (we typically respond within 24 hours)</li><li><strong>WeChat:</strong> ID "BowenManchester" for Chinese-speaking families</li><li><strong>Contact Form:</strong> Fill out the form on our <a href="/contact">Contact Us</a> page</li><li><strong>In Person:</strong> Visit us during opening hours (Saturday-Sunday, 9 AM - 5 PM)</li></ul><p>You can also follow us on social media for updates, event photos, and student achievements. We look forward to welcoming your family to Bowen Education!</p>',
  'How can I contact you for more information?',
  '<p>We''d love to hear from you! You can reach us through multiple channels:</p><ul><li><strong>Phone:</strong> 07888 760868 (Monday-Friday, 9 AM - 5 PM; Saturday-Sunday, 9 AM - 1 PM)</li><li><strong>Email:</strong> <a href="mailto:info@boweneducation.co.uk">info@boweneducation.co.uk</a> (we typically respond within 24 hours)</li><li><strong>WeChat:</strong> ID "BowenManchester" for Chinese-speaking families</li><li><strong>Contact Form:</strong> Fill out the form on our <a href="/contact">Contact Us</a> page</li><li><strong>In Person:</strong> Visit us during opening hours (Saturday-Sunday, 9 AM - 5 PM)</li></ul><p>You can also follow us on social media for updates, event photos, and student achievements. We look forward to welcoming your family to Bowen Education!</p>',
  '如何联系你们获取更多信息？',
  '<p>我们很乐意听到您的声音！您可以通过多种渠道联系我们：</p><ul><li><strong>电话：</strong>07888 760868（周一至周五，上午9点-下午5点；周六至周日，上午9点-下午1点）</li><li><strong>电子邮件：</strong><a href="mailto:info@boweneducation.co.uk">info@boweneducation.co.uk</a>（我们通常在24小时内回复）</li><li><strong>微信：</strong>ID "BowenManchester" 中文家庭可加</li><li><strong>联系表单：</strong>在我们的<a href="/contact">联系我们</a>页面填写表单</li><li><strong>亲临现场：</strong>在开放时间来访（周六至周日，上午9点-下午5点）</li></ul><p>您还可以在社交媒体上关注我们，了解更新、活动照片和学生成就。我们期待欢迎您的家庭加入博文教育！</p>',
  21,
  1,
  0,
  0,
  0,
  0,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
);

-- 更新完成
-- 新增 15 个 FAQ，总计 18 个（包括已有的3个）
